import "./main-b7_1VyY-.js";
import { e as r, c as t, b as o, h as n, t as c, u as p, v as i, k as l, w as d, f as g, d as m, E as C, g as w, i as f, z as u, A as x, l as y, m as R, x as S, p as k, s as B, j as F, n as h, o as v, B as I, r as b, G as j, a as z, F as A, C as D, y as E, D as G } from "./qx-WwCuLWFC.js";
export {
  r as cls,
  t as col,
  o as color,
  n as cursor,
  c as drawImage,
  p as drawImageRect,
  i as drawRect,
  l as drawText,
  d as fillRect,
  g as frame,
  m as getBgColor,
  C as getContext,
  w as getFgColor,
  f as init,
  u as key,
  x as keyp,
  y as locate,
  R as measure,
  S as playSound,
  k as print,
  B as printBox,
  F as printCentered,
  h as printChar,
  v as printRect,
  I as redefineColors,
  b as render,
  j as restoreScreen,
  z as row,
  A as saveScreen,
  D as setFont,
  E as spr,
  G as stopSound
};
